### ISSUE TITLE
[Bug]: win11下启动项目时，代码报错

### ISSUE THREAD

**Issue by CoderSerio** [DevCloudFE/react-devui#289]
## 🙁 Actual behavior

`tools\base64-data.ts`的27行：
```ts
table.write([filePath.match(/(?<=packages\/)[\s\S]+?(?=\/)/)![0], file]);
```
`[filePath.match(/(?<=packages\/)[\s\S]+?(?=\/)/)`可能为null，导致报错。

报错信息如下所示：

![image](https://github.com/DevCloudFE/react-devui/assets/79406469/02d71382-866b-4c90-8c98-0770fe5c961d)

## 🙂 Expected behavior

能够正常运行

## ⏯ Steps to Reproduce

执行以下命令：
```shell
yarn serve:site
```

### 🕗 Version & Environment

os: windows 11
node: v16.19.0
yarn: 1.22.19

**Comment by CoderSerio** [comment]
我想尝试解决一下这个问题

**Comment by xiejay97** [comment]
> 我想尝试解决一下这个问题

可以的，这里是没处理Windows下的路径兼容
