### ISSUE TITLE
Component contribution(组件贡献)

### ISSUE THREAD

**Issue by xiejay97** [DevCloudFE/react-devui#33]
Make sure to read [README](https://github.com/xiejay97/react-devui/blob/main/README.md) before development.
开发之前确保阅读了  [README](https://github.com/xiejay97/react-devui/blob/main/README.md)。

Some components are not considered for implementation for the time being, because we want the number of components in the component library to be as small as possible, and some components can be implemented through expansion or combination.
某些组件暂时不考虑实现，因为我们希望组件库的组件数量尽可能的少，可以通过拓展或者组合的方式实现某些组件。

Component development can refer to:
组件开发可参考：
- [devui](https://devui.design/components/en-us/overview)
- [antd](https://ant.design/components/overview/)
- [mui](https://mui.com/components/)

**Be sure to confirm Props with me before developing components. Only after confirming Props, the component is considered to be under development!**
**开发组件前务必和我确认Props。只有确认过Props，才认为组件是在开发中！**

**Notice! ! ! According to the progress of the project, I will complete some components that are not under development by myself.**
**注意！！！依据项目进展，某些还没开发中的组件我会自己完成。**

The following is a list of components that have been confirmed for development:
下面是已确认开发的组件列表：

## General | 通用

- [x] Button 按钮  @xiejay97
- [x] Compose 组合 @xiejay97

## Layout | 布局

- [x] Affix 固钉 @xiejay97
- [ ] BackTop 回到顶部  @c0dedance
- [ ] Grid 栅格 @xiejay97
- [x] Separator 分隔符  @xiejay97 
- [ ] Splitter 分割器 待认领

## Navigation | 导航

- [x] Anchor 锚点 @xiejay97
- [x] Dropdown 下拉菜单 @xiejay97
- [x] Menu 导航菜单 @xiejay97
- [x] Pagination 分页  @xiejay97
- [x] Tabs 页签面板  @xiejay97

## Data Display | 数据展示

- [ ] Avatar 头像 @zxlfly
- [ ] Badge 徽章 @AlanLee97
- [ ] Card 卡片 @c0dedance
- [ ] Carousel 走马灯 @aouos
- [ ] Collapse 折叠面板 @Kiki-Q 
- [ ] Comment 评论 @GeorgeLeoo
- [x] Empty 空状态 @xiejay97
- [ ] Progress 进度条 @Pineapple0919
- [ ] Skeleton 骨架屏 待认领
- [ ] Table 表格 待认领
- [x] Tag 标签 @xiejay97 
- [ ] Timeline 时间轴 @kevinawe
- [x] Tooltip 文字提示 @xiejay97
- [ ] Tree View 树视图 @NidusP

## Data Entry | 数据录入

- [ ] AutoComplete 自动完成 @zxlfly
- [x] Cascader 级联选择 @xiaoboRao
- [x] Checkbox 多选框 @xiejay97
- [ ] DatePicker 日期选择器（参考[DatePickerPro](https://devui.design/components/zh-cn/datepickerPro/demo)） 待认领
- [x] Form 表单 @xiejay97
- [ ] EditableSelect 可输入下拉框 待认领
- [x] Input 输入框 @xiejay97 
- [ ] InputNumber 数字输入框 待认领
- [ ] MultiAutoComplete 多项自动完成 @zxlfly
- [x] Radio 单选组
- [x] Rate 评分 @Pineapple0919
- [x] Select 选择器 @xiejay97 
- [x] Slider 滑动输入条 @tjw-javen
- [x] Switch 开关 @big-bomp
- [x] Textarea 文本域 @xiejay97
- [ ] TimePicker 时间选择器 待认领
- [ ] Transfer 穿梭框 @git-Where
- [ ] TreeSelect 树形选择器 待认领
- [ ] Upload上传 @zxlfly

## Feedback | 反馈

- [ ] Alert 警告提示 @c0dedance
- [x] Drawer 抽屉 @xiejay97
- [ ] Loading 加载中 @huanganfree
- [ ] Modal 对话框 @SleepDevil
- [x] Notification 通知 @xiejay97
- [ ] Popover 悬浮提示 @SleepDevil
- [x] Toast 提示 @xiejay97

**Comment by xiejay97** [comment]
component(组件): Tag
img(图片):
![image](https://user-images.githubusercontent.com/64340763/144958527-d6db5172-ed37-46e4-b85e-d6e8acb4fcf8.png)

**Comment by big-bomp** [comment]
认领 font + toggle

**Comment by tjw-javen** [comment]
认领slider

**Comment by c0dedance** [comment]
认领tag、backtop、card、Alert

**Comment by xiaoboRao** [comment]
认领cascader

**Comment by aouos** [comment]
认领 carousel 跑马灯（轮播图）

**Comment by big-bomp** [comment]
**components(组件)**
font + toggle
**img(图片)**
![image](https://user-images.githubusercontent.com/76605831/144959203-ddbc1b4a-f9f2-4546-b312-5886b4df00d6.png)
![image](https://user-images.githubusercontent.com/76605831/144959238-e3f1de00-8bb1-4c38-8872-f22198a21a38.png)

**Comment by Pineapple0919** [comment]
认领 Rate、Progress
![image](https://user-images.githubusercontent.com/74694190/144959408-489404a9-4aee-4a07-9154-2f81a9e522ee.png)
![image](https://user-images.githubusercontent.com/74694190/144959446-17d2300b-3ceb-4456-9a19-ca031ea9a41f.png)

**Comment by lnzhangsong** [comment]
认领 ReadTip

**Comment by kevinawe** [comment]
认领 timeAxis 时间轴
![image](https://user-images.githubusercontent.com/28033581/144959850-668a84a0-f26b-49c7-b9cc-4f5cbe7c2037.png)

**Comment by GeorgeLeoo** [comment]
认领评论组件
![image](https://user-images.githubusercontent.com/48482395/144960479-3c812a1c-ada7-4dc9-a9cd-722d586972b0.png)

**Comment by zzztwx** [comment]
认领checkbox

![`~THX%5_2ZG4C1@UI XU@H5](https://user-images.githubusercontent.com/54833732/144960600-7750d0a3-6738-4e16-a1f6-300d857d4d3c.png)

**Comment by zhouhuan327** [comment]
认领Search组件
![image](https://user-images.githubusercontent.com/24819600/144960858-f4236d4d-172c-4f1e-b964-6807d628ad26.png)

**Comment by SleepDevil** [comment]
认领Modal、Popover组件
![image](https://user-images.githubusercontent.com/55879038/144962272-beb43b2c-c0aa-4e83-93da-86aca71e037d.png)
![image](https://user-images.githubusercontent.com/55879038/144962300-d0eebf08-3934-468e-a29a-792ef69db4aa.png)

**Comment by banlify** [comment]
认领 Status 组件
![](https://img.fy6b.com/2021/12/07/257e6849a7794.png)

**Comment by panyongxu** [comment]
认领readTip
![image](https://user-images.githubusercontent.com/26707568/144962331-60886d75-9cd9-4e27-ac90-c5a0e3d54ef9.png)

**Comment by git-Where** [comment]
认领Transfer
![image](https://user-images.githubusercontent.com/16344566/144962518-52ad9297-ca7a-4a8b-a7a8-2f5748e1f504.png)

**Comment by zxlfly** [comment]
认领Fullscreen 全屏
![QQ截图20211207124659](https://user-images.githubusercontent.com/26324442/144968123-f8b89934-79b0-40ce-8008-ae46812b2091.png)

**Comment by zxlfly** [comment]
认领ImagePreview 图片预览
![222](https://user-images.githubusercontent.com/26324442/144968406-cdd5e5e4-a406-40d3-9d3e-db722d87bcf8.png)

**Comment by AlanLee97** [comment]
认领Badge 徽标组件

![image](https://user-images.githubusercontent.com/42601044/144969417-bded143b-f56a-4a3c-ab56-47c687bb7cde.png)

**Comment by huanganfree** [comment]
认领loading组件
![Dingtalk_20211207130609](https://user-images.githubusercontent.com/41275935/144970021-7cd3884a-b48f-4e58-9974-e4ebfc1a5503.jpg)

**Comment by xiejay97** [comment]
This is the place that was checked last time, there will be new component development later, please directly @me
这里为上次查看到地方，后面有新的组件开发，请直接@我

**Comment by zxlfly** [comment]
认领Avatar 头像
![111](https://user-images.githubusercontent.com/26324442/144979128-b2101114-3004-40c3-ad3d-dd333f2b73f6.png)

**Comment by zxlfly** [comment]
认领Upload  上传
![2222](https://user-images.githubusercontent.com/26324442/144979358-8836adc9-37a0-4246-87df-55b5aba2cf77.png)

**Comment by zxlfly** [comment]
认领AutoComplete 自动补全、MultiAutoComplete 多项自动补全
![888](https://user-images.githubusercontent.com/26324442/144979579-7828cfe9-a817-463f-a59a-2b9e4132cb46.png)
![7777](https://user-images.githubusercontent.com/26324442/144979584-ae8e130d-a1a4-4804-b7a5-a4be51ba34b4.png)

**Comment by zxlfly** [comment]
@xiejay97

**Comment by zxlfly** [comment]
> 认领AutoComplete 自动补全、MultiAutoComplete 多项自动补全 ![888](https://user-images.githubusercontent.com/26324442/144979579-7828cfe9-a817-463f-a59a-2b9e4132cb46.png) ![7777](https://user-images.githubusercontent.com/26324442/144979584-ae8e130d-a1a4-4804-b7a5-a4be51ba34b4.png)

@xiejay97

**Comment by zxlfly** [comment]
@xiejay97

**Comment by xiejay97** [comment]
This is the place that was checked last time, there will be new component development later, please directly @xiejay97
这里为上次查看到地方，后面有新的组件开发，请直接@xiejay97

**Comment by NidusP** [comment]
tree组件可以认领吗?@xiejay97

**Comment by xiejay97** [comment]
> tree组件可以认领吗?@xiejay97

可以

**Comment by NidusP** [comment]
> 

认领tree组件

**Comment by Kiki-Q** [comment]
认领Panel+Accordion
![image](https://user-images.githubusercontent.com/23020999/146353155-f3cacada-5001-41bc-84d5-8386e4c5ce18.png)
![image](https://user-images.githubusercontent.com/23020999/146353204-ad2ee6ef-c020-421f-9c67-07c2b18381cb.png)

**Comment by xiejay97** [comment]
> Panel

Panel不考虑，Accordion其实是菜单，你可以考虑做Collapse折叠面板

**Comment by Kiki-Q** [comment]
可以呀？我刚查看了一下devui.design没有collapse，element UI有，但是相对accordion的api简单了些，我是按哪种需求来完成呢？？

发自我的iPhone

**Comment by xiejay97** [comment]
> 可以呀？我刚查看了一下devui.design没有collapse，element UI有，但是相对accordion的api简单了些，我是按哪种需求来完成呢？？ 发自我的iPhone
> […](#)
> 在 2021年12月17日，上午11:59，Xie Jay ***@***.***> 写道： ﻿ Panel Panel不考虑，Accordion其实是菜单，你可以考虑做Collapse折叠面板 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.

这个可以自己决定

**Comment by Kiki-Q** [comment]
好的，那我确定认领了～

发自我的iPhone

**Comment by qiugu** [comment]
大佬，认领transition、collapseTransition组件单元测试，顺便请教一下，怎么进行过渡动画的测试呢

**Comment by xiejay97** [comment]
> 大佬，认领transition、collapseTransition组件单元测试，顺便请教一下，怎么进行过渡动画的测试呢

动画测试我还真不了解，感兴趣的话可以联系我一起讨论

**Comment by xiejay97** [comment]
> 好的，那我确定认领了～ 发自我的iPhone
> […](#)
> 在 2021年12月17日，下午6:25，Xie Jay ***@***.***> 写道： ﻿ 可以呀？我刚查看了一下devui.design没有collapse，element UI有，但是相对accordion的api简单了些，我是按哪种需求来完成呢？？ 发自我的iPhone … 在 2021年12月17日，上午11:59，Xie Jay @.***> 写道： ﻿ Panel Panel不考虑，Accordion其实是菜单，你可以考虑做Collapse折叠面板 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented. 这个可以自己决定 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.

好的，不过开发之前确保设计好props即可

**Comment by 224137748** [comment]
嗨 @xiejay97 ，考虑做Breadcrumbs面包屑导航组件吗，如果要做的话我想申请认领了。

**Comment by Meet-student** [comment]
认领Splitter 分割器

**Comment by leohai** [comment]
@xiejay97 
认领InputNumber 数字输入框组件
![image](https://user-images.githubusercontent.com/34530234/160525101-a58fa454-3acd-46cd-a050-e93101741f31.png)

**Comment by xiejay97** [comment]
> @xiejay97 认领InputNumber 数字输入框组件 ![image](https://user-images.githubusercontent.com/34530234/160525101-a58fa454-3acd-46cd-a050-e93101741f31.png)

没有inputnumber这个组件，数字输入已在input实现😬

**Comment by leohai** [comment]
> > @xiejay97 认领InputNumber 数字输入框组件 ![image](https://user-images.githubusercontent.com/34530234/160525101-a58fa454-3acd-46cd-a050-e93101741f31.png)
> 
> 没有inputnumber这个组件，数字输入已在input实现😬
Skeleton 呢  或者 Splitter
![image](https://user-images.githubusercontent.com/34530234/160547675-864b45f1-a820-438f-89cb-219a8f790cf1.png)
![image](https://user-images.githubusercontent.com/34530234/160547889-b396e5b8-f406-43ac-864c-0c1d17669f0a.png)

**Comment by xiejay97** [comment]
close because no update
